version: "3.8"
    
services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    volumes:
#      - ./influxdb-storage:/var/lib/influxdb2:rw
      - $PWD/data:/var/lib/influxdb2:rw
      - $PWD/config:/etc/influxdb2:rw
    env_file:
      - .env
#    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.28.2
    container_name: telegraf1
    hostname: telegraf1
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - 8092:8092

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
